import { JetBrains_Mono } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const jetBrains_Mono = JetBrains_Mono({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "CodeBlox - World's First AI Native IDE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Include React, ReactDOM, and Babel Standalone via CDN */}
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script
          src="https://unpkg.com/react@17/umd/react.development.js"
          crossOrigin="anonymous"
        ></script>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script
          src="https://unpkg.com/react-dom@17/umd/react-dom.development.js"
          crossOrigin="anonymous"
        ></script>
        {/* Load Babel synchronously */}
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script
          src="https://unpkg.com/@babel/standalone/babel.min.js"
          crossOrigin="anonymous"
        ></script>
      </Head>

      <body className={jetBrains_Mono.className}>{children}</body>
    </html>
  );
}
